#!/bin/bash

NAME=""OB
BASECALLS=""
SAMPLESHEET=""
if [ $# -ne 3 ] ; then
    echo "What's the Name? Where are the BaseCalls and the Samplesheet?"
    echo "usage: $0 name basecalldir samplesheet"
    exit 1
else
    export NAME="$1"
    export BASECALLS="$2"
    export SAMPLESHEET="$3"
fi


cat <<EOF > /tmp/template_script_tmp.in

. /share/apps/casava/1.8.2/intel/env.sh

cd \$UNALIGNED

make -j8 \
  1> \$OUT_DIR/make.stdout \
  2> \$OUT_DIR/make.stderr

EOF

export MAKEPBS="make_pbs_script.ml -template /tmp/template_script_tmp.in -nodes-ppn 1 8"

echo "Creating ${NAME}_M0 ${NAME}_M1"
mkdir ${NAME}_M0 ${NAME}_M1

. /share/apps/casava/1.8.2/intel/env.sh

export FCC_OPTION=" --fastq-cluster-count 800000000"

configureBclToFastq.pl $FCC_OPTION \
  --input-dir $BASECALLS \
  --output-dir ${NAME}_M0/Unaligned \
  --sample-sheet $SAMPLESHEET \
  --mismatches 0 

$MAKEPBS -var UNALIGNED=$PWD/${NAME}_M0/Unaligned B2Fpbs_${NAME}_M0

configureBclToFastq.pl $FCC_OPTION \
  --input-dir $BASECALLS \
  --output-dir ${NAME}_M1/Unaligned \
  --sample-sheet $SAMPLESHEET \
  --mismatches 1

$MAKEPBS  -var UNALIGNED=$PWD/${NAME}_M1/Unaligned  B2Fpbs_${NAME}_M1


