#!/bin/bash

export ANALYZE_ROOT=""
if [ $# -ne 1 ] ; then
    echo "Where is the root of the analysis?"
    echo "usage: $0 analyze_root"
    exit 1
else
    export ANALYZE_ROOT="$1"
fi

export M0_U=$ANALYZE_ROOT/Mismatch_0/Unaligned
export M1_U=$ANALYZE_ROOT/Mismatch_1/Unaligned
if [ -d $M0_U ] && [ -d $M1_U ] ; then
    echo "OK This seems standard"
else
    echo "Can't find $M0_U or $M1_U"
    exit 1
fi

cat <<EOF > /tmp/template_script_tmp.in
check_fastqs.ml \$ANALYZE_DIR/ > \$OUT_DIR/Check_FASTQs_\$NAME.txt

EOF

function make_one () {
    make_pbs_script.ml \
	-var ANALYZE_DIR=$ANALYZE_ROOT/$1 \
	-template /tmp/template_script_tmp.in \
	$2
}

PROJECTS_0=`find $M0_U -maxdepth 1  -name "Project_*" -type d`
PROJECTS_1=`find $M1_U -maxdepth 1  -name "Project_*" -type d`

echo $PROJECTS_0
echo $PROJECTS_1

for proj in $PROJECTS_0; do
    NAME="CFM0`basename $proj`"
    make_one $proj $NAME
done
for proj in $PROJECTS_1; do
    NAME="CFM1`basename $proj`"
    make_one $proj $NAME
done


